{{- if .Values.createBucketsAndTask.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-task-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  task.flux: |+
    {{ .Values.createBucketsAndTask.task.script | nindent 4 }}
{{- end }}
