image:
  repository: influxdb
  tag: 2.7.4-alpine
  pullPolicy: IfNotPresent
  ## If specified, use these secrets to access the images
  # pullSecrets:
  #   - registry-secret

## Annotations to be added to InfluxDB pods
podAnnotations: {}

## Labels to be added to InfluxDB pods
podLabels: {}

nameOverride: ""
fullnameOverride: ""

## Configure resource requests and limits
resources: {}

## Node labels for pod assignment
nodeSelector: {}

## Tolerations for pod assignment
tolerations: []

## Affinity for pod assignment
affinity: {}

securityContext: {}

## Customize liveness, readiness and startup probes
livenessProbe: {}

readinessProbe: {}

startupProbe:
  enabled: false

## Extra environment variables to configure influxdb
env: {}

## Create default user through docker entrypoint
adminUser:
  organization: "influxdata"
  bucket: "default"
  user: "admin"
  retention_policy: "0s"
  password: ""
  token: ""

## Persist data to a persistent volume
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 50Gi
  mountPath: /var/lib/influxdb2
  subPath: ""

## Add custom volume and volumeMounts
# volumes:
# mountPoints:

## Allow executing custom init scripts
initScripts:
  enabled: false

## Specify a service type
service:
  type: ClusterIP
  port: 80
  targetPort: 8086
  annotations: {}
  labels: {}
  portName: http

serviceAccount:
  create: true
  name:
  annotations: {}

ingress:
  enabled: false
  tls: false
  # secretName: my-tls-cert
  hostname: influxdb.foobar.com
  annotations: {}
  path: /

## Pod disruption budget configuration
pdb:
  create: true
  minAvailable: 1

# --- Configuration for aggregated buckets and the task that populates data into them---
createBucketsAndTask:
  enabled: true  # Toggle to enable or disable bucket and task creation
  buckets:
    - name: "default_agg_topic"   # Aggregated bucket for topic
      retentionPolicy: "0s"     # Retention policy (adjust as needed)
    - name: "default_agg_stats"   # Aggregated bucket for stats
      retentionPolicy: "0s"
    - name: "default_agg_kpi"     # Aggregated bucket for KPI
      retentionPolicy: "0s"
  task:
    name: "aggregate_data"
    script: |+
#TODO
    #add script for the task
# --- Configuration for aggregated buckets and task ends here ---
